  # This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Solution (NET Core)
      run: dotnet build --no-restore -c debug
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.2
    - name: Build Solution
      run: msbuild MoreSettings.sln /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
